apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mmcontrollers.kopf.dev
  namespace: modelmesh-serving
spec:
  scope: Namespaced
  group: kopf.dev
  names:
    kind: MmController
    plural: mmcontrollers
    singular: mmcontroller
    shortNames:
      - mmcs
      - mmc
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mm-operator
  namespace: modelmesh-serving
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: mm-operator
  template:
    metadata:
      labels:
        application: mm-operator
    spec:
      serviceAccountName: mm-sa
      containers:
      - name: the-only-one
        image: quandvrobusto/mm-operator:0.0.1