apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: intrusion-detection
  namespace: modelmesh-serving
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
    serving.kserve.io/secretKey: localMinIO
spec:
  predictor:
    model:
      modelFormat:
        name: vae
        version: "1"
      storageUri: s3://modelmesh-example-models/custom/vae
---
apiVersion: kopf.dev/v1
kind: MmController
metadata:
  name: intrusion-detection
  namespace: modelmesh-serving
spec:
  scaleTargetRef: 
    name: vae-0.x
    namespace: modelmesh-serving
  interval: 1
  query: >
    rate(
      container_cpu_system_seconds_total{
        namespace='modelmesh-serving',
        pod=~'modelmesh-serving-vae-0.x-.*',
        container='mlserver'}[1m]
    )
  threshold: 0.01
  minReplicas: 1
  maxReplicas: 2